name: Publish PlatformIO Library
on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install PlatformIO
        run: pip install -U platformio

      - name: PLATFORMIO_AUTH_TOKEN
        run: echo $PLATFORMIO_AUTH_TOKEN

      - name: Publish library
        run: pio pkg publish
